services:
  spark-master:
    image: apache/spark:4.0.1
    container_name: spark-master
    hostname: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "8080:8080" 
      - "7077:7077"  
      - "4040:4040"  
    volumes:
      - ./src:/app/src
      - ./notebooks:/app/notebooks
      - ./spark-apps:/app/spark-apps
      - ./spark-data:/app/spark-data
      - ./pyproject.toml:/app/pyproject.toml
      - ./uv.lock:/app/uv.lock
      - ./data:/app/data
    networks:
      - spark-network

  spark-worker-1:
    image: apache/spark:4.0.1
    container_name: spark-worker-1
    hostname: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=1g
      - SPARK_WORKER_WEBUI_PORT=8081
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    ports:
      - "8081:8081"  
    volumes:
      - ./src:/app/src
      - ./notebooks:/app/notebooks
      - ./spark-apps:/app/spark-apps
      - ./spark-data:/app/spark-data
      - ./pyproject.toml:/app/pyproject.toml
      - ./uv.lock:/app/uv.lock
      - ./data:/app/data
    depends_on:
      - spark-master
    networks:
      - spark-network

  spark-worker-2:
    image: apache/spark:4.0.1
    container_name: spark-worker-2
    hostname: spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=1g
      - SPARK_WORKER_WEBUI_PORT=8081
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    ports:
      - "8082:8081"  
    volumes:
      - ./src:/app/src
      - ./notebooks:/app/notebooks
      - ./spark-apps:/app/spark-apps
      - ./spark-data:/app/spark-data
      - ./pyproject.toml:/app/pyproject.toml
      - ./uv.lock:/app/uv.lock
      - ./data:/app/data
    depends_on:
      - spark-master
    networks:
      - spark-network

  spark-app:
    build: .
    container_name: spark-app
    environment:
      - SPARK_MASTER_URL=spark://spark-master:7077
    ports:
      - "8888:8888"
    depends_on:
      - spark-master
    networks:
      - spark-network
    volumes:
      - ./src:/app/src
      - ./notebooks:/app/notebooks
      - ./spark-apps:/app/spark-apps
      - ./spark-data:/app/spark-data
      - ./pyproject.toml:/app/pyproject.toml
      - ./uv.lock:/app/uv.lock
      - ./data:/app/data
    restart: unless-stopped

networks:
  spark-network:
    driver: bridge