services:
  spark-master:
    image: apache/spark:4.0.1
    container_name: spark-master
    hostname: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "8080:8080" 
      - "7077:7077"
    networks:
      - spark-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 3

  spark-worker-1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spark-worker-1
    hostname: spark-worker-1
    environment:
      - ROLE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=1g
      - SPARK_WORKER_WEBUI_PORT=8081
      - PYSPARK_PYTHON=/app/.venv/bin/python
      - PYSPARK_DRIVER_PYTHON=/app/.venv/bin/python
    ports:
      - "8081:8081"
    volumes:
      - ./src:/app/src:ro
      - ./notebooks:/app/notebooks:ro
      - ./spark-apps:/app/spark-apps:ro
      - ./spark-data:/app/spark-data
      - ./data:/app/data:ro
    depends_on:
      spark-master:
        condition: service_healthy
    networks:
      - spark-network

  spark-worker-2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spark-worker-2
    hostname: spark-worker-2
    environment:
      - ROLE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=1g
      - SPARK_WORKER_WEBUI_PORT=8081
      - PYSPARK_PYTHON=/app/.venv/bin/python
      - PYSPARK_DRIVER_PYTHON=/app/.venv/bin/python
    ports:
      - "8082:8081"
    volumes:
      - ./src:/app/src:ro
      - ./notebooks:/app/notebooks:ro
      - ./spark-apps:/app/spark-apps:ro
      - ./spark-data:/app/spark-data
      - ./data:/app/data:ro
    depends_on:
      spark-master:
        condition: service_healthy
    networks:
      - spark-network

  spark-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spark-app
    hostname: spark-app
    environment:
      - ROLE=driver
      - SPARK_MASTER_URL=spark://spark-master:7077
      - PYSPARK_PYTHON=/app/.venv/bin/python
      - PYSPARK_DRIVER_PYTHON=/app/.venv/bin/python
    ports:
      - "8888:8888"
    volumes:
      - ./src:/app/src
      - ./notebooks:/app/notebooks
      - ./spark-apps:/app/spark-apps
      - ./spark-data:/app/spark-data
      - ./data:/app/data
    depends_on:
      spark-master:
        condition: service_healthy
    networks:
      - spark-network
    restart: unless-stopped

networks:
  spark-network:
    driver: bridge